# Generated by Django 3.0.1 on 2020-01-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_compare_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='title',
        ),
    ]
