# Generated by Django 3.0.1 on 2020-01-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_compare_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='document',
            field=models.FileField(default='excel', upload_to='../accounts/files'),
        ),
        migrations.AddField(
            model_name='compare',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
