# Generated by Django 3.0.1 on 2020-01-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='content',
        ),
        migrations.AddField(
            model_name='compare',
            name='document',
            field=models.FileField(default='documents/', upload_to=''),
        ),
    ]
