# Generated by Django 3.0.1 on 2020-01-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200119_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compare',
            name='document',
        ),
    ]
