# Generated by Django 3.0.1 on 2020-01-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200120_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('document', models.FileField(default='', upload_to='./accounts')),
            ],
        ),
        migrations.DeleteModel(
            name='compare',
        ),
    ]
