# Generated by Django 3.0.1 on 2020-01-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='Title',
            new_name='title',
        ),
    ]
